steps:
  - task: Bash@3
    displayName: 'Generate Describe'
    inputs:
      targetType: 'inline'
      script: |
        sfdx force:mdapi:describemetadata -u $(sfdxUsername) -f describe.log --apiversion $(API_VERSION)
        statusCode=$?

        echo "Status code: $statusCode"
      workingDirectory: $(Pipeline.Workspace)/$(PATH_SALESFORCE)
